from backend.api.v1.schemas.calc_input import CalcInputV1, InternalWallIn, OpeningIn, OpeningTypes

INPUT_DATA = CalcInputV1(
    length=8,
    width=6,
    wall_height=2.7,
    total_floors=1,
    is_fronton_short=True,
    stud_spacing=0.63,
    joist_spacing=0.63,
    rafter_spacing=0.63,
    wall_section_id="BOARD_50x150x6",
    ground_overlap_section_id="BOARD_50x200x6",
    interfloor_overlap_section_id="BOARD_50x200x6",
    attic_overlap_section_id="BOARD_50x150x6",
    roof_section_id="BOARD_50x200x6",
    lath_section_id="BOARD_25x100x6",
    counter_lath_section_id="BAR_50x50x6",
    waste_factor=1.1,
    roof_pitch_deg=35.0,
    eave_overhang=0.6,
    gable_overhang=0.6,
    lath_step=0.35,
    has_ground_overlap=True,
    has_interfloor_overlap=False,
    has_attic_overlap=True,
    ground_blocking_rows=4,
    interfloor_blocking_rows=4,
    attic_blocking_rows=4,
    external_openings=[
        OpeningIn(type=OpeningTypes.WINDOW, width=1.4, height=1.2, quantity=6),
        OpeningIn(type=OpeningTypes.DOOR, width=0.9, height=2.1, quantity=1),
    ],
    internal_walls=[
        InternalWallIn(length=5.7, openings=[OpeningIn(type=OpeningTypes.DOOR, width=0.9, height=2.1, quantity=2)]),
        InternalWallIn(length=3.78, openings=[OpeningIn(type=OpeningTypes.DOOR, width=0.9, height=2.1, quantity=1)]),
    ],
)
