from enum import Enum


class GroupEnum(str, Enum):
    EXTERNAL_WALLS = "EXTERNAL_WALLS"
    INTERNAL_WALLS = "INTERNAL_WALLS"
    GROUND_OVERLAP = "GROUND_OVERLAP"
    INTERFLOOR_OVERLAP = "INTERFLOOR_OVERLAP"
    ATTIC_OVERLAP = "ATTIC_OVERLAP"
    ROOF_STRUCT = "ROOF_STRUCT"
    ROOF_LATH = "ROOF_LATH"


class ElementEnum(str, Enum):
    STUDS = "STUDS"
    PLATES_BOTTOM = "PLATES_BOTTOM"
    PLATES_TOP = "PLATES_TOP"
    OPENING_KING = "OPENING_KING"
    OPENING_JACK = "OPENING_JACK"
    OPENING_HEADER = "OPENING_HEADER"
    OPENING_SILL = "OPENING_SILL"
    JOISTS = "JOISTS"
    RIM = "RIM"
    BLOCKING = "BLOCKING"
    RAFTERS = "RAFTERS"
    RIDGE = "RIDGE"
    FLY_RAFTERS = "FLY_RAFTERS"
    TIES = "TIES"
    LATH = "LATH"
